name: TicketMaster CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region ap-south-1 | \
        docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

    - name: Build & Push Backend
      run: |
        docker build -t backend:latest -f docker/backend.Dockerfile .
        docker tag backend:latest ${{ secrets.ECR_REGISTRY }}/ticketmaster-backend:latest
        docker push ${{ secrets.ECR_REGISTRY }}/ticketmaster-backend:latest

    - name: Build & Push Frontend
      run: |
        docker build -t frontend:latest -f docker/frontend.Dockerfile .
        docker tag frontend:latest ${{ secrets.ECR_REGISTRY }}/ticketmaster-frontend:latest
        docker push ${{ secrets.ECR_REGISTRY }}/ticketmaster-frontend:latest


    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          chmod +x /home/ec2-user/scripts/deploy.sh
          /home/ec2-user/scripts/deploy.sh ${{ secrets.ECR_REGISTRY }}
